name: build docker image and push to ghcr.io
description: Build Docker image from folder and push the docker image to GitHub Container Registry

inputs:
  context:
    description: 'Build context (directory to build from)'
    required: true

runs: 
  using: composite
  steps:

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        # This is the GitHub username of the user who triggered the workflow
        username: ${{ github.actor }}
        # This is the GitHub token that has permissions to push to the registry
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: ${{ inputs.context }}
        push: true
        tags: exampledeployment/backend:latest

