name: build docker image and push to ghcr.io
description: Build Docker image from folder and push the docker image to GitHub Container Registry

inputs:
  context:
    description: 'Build context (directory to build from)'
    required: true
  image_name:
    description: 'Name of the Docker image'
    required: true
  username:
    description: 'GitHub username'
    required: true
  password:
    description: 'GitHub token'
    required: true

runs: 
  using: composite
  steps:

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        # This is the GitHub username of the user who triggered the workflow
        username: ${{ inputs.username }}
        # This is the GitHub token that has permissions to push to the registry
        password: ${{ inputs.password }}

    - name: Build Docker image
      uses: docker/build-push-action@v5
      with:
        context: ${{ inputs.context }}
        push: false
        tags: ghcr.io/${{ github.repository_owner }}/${{ inputs.image_name }}:latest

    - name: Scan Docker image for vulnerabilities
      uses: aquasecurity/trivy-action@0.31.0
      with:
        image-ref: ghcr.io/${{ github.repository_owner }}/${{ inputs.image_name }}:latest
        format: table
        exit-code: 1
        ignore-unfixed: true

    - name: Push Docker image
      uses: docker/build-push-action@v5
      with:
        context: ${{ inputs.context }}
        push: true
        tags: ghcr.io/${{ github.repository_owner }}/${{ inputs.image_name }}:latest