name: Backend Python Code Quality and Security

on:
  pull_request:
    paths:
      - 'backend/**/*.py'
      - 'backend/README.md'

jobs:
  quality-and-security:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black flake8 bandit

      - name: Check formatting with black
        run: |
          black --check backend

      - name: Lint with flake8
        run: |
          flake8 backend

      - name: Security check with bandit
        run: |
          bandit -r backend